### ISSUE TITLE
3.2  Subsystem Decomposition

### ISSUE THREAD

**Issue by VilfredSikker** [NoticeMeDan/planning-poker#39]

**Comment by IMarnild** [comment]
cf. OOSE Chapter 6.3

**Comment by oliverjuhl** [comment]
Jeg smider lige et revideret subsystem diagram ind, hvor jeg tager udgangspunkt i case study (ARENA) fra bogen. 
![system decomposition](https://user-images.githubusercontent.com/37775772/48889539-83b32300-ee36-11e8-84de-3528ee886297.png)

**Comment by oliverjuhl** [comment]
Og med følgende tekst til rapport:
PlanningPokerClient subsystem:
This subsystem is responsible for the user interface, which are presented to the user. The subsystem handles all interactions with our application, and captures user input and events. These are propagated further down the "subsystem chain" to a given subsystem, that are responsible for a given event or input. 

Authentication subsystem: 
This subsystem is responsible for the login of the users. The authentication system makes sure to assign the users to the correct user-role (Scrum master and Team member) in the application. Based on these roles, the subsystem will provide access to different parts in the \textit{SessionSubstem}. 

UserManagement subsystem:
This subsystem is responsible for the user information. We are using Azure Active Directory, which allows the user to manage it's profile. This is for example the possibility of resetting passwords.

SessionManagement subsystem:
This subsystem is dependent on the role you have been provided in the \textit{AuthenticationSubsystem}. You can either create a session, if you are a scrum master or participate in a session, if you are a team member. 

Notification subsystem:
This subsystem handles the events from \textit{SessionSubsystem} and notifies the users. During a session the \textit{NotificationSubsystem} will update the user on events and the results of a session is being send to the \textit{SummarySubsystem}.

Summary subsystem:
This subsystem is responsible for providing summaries to the users, when sessions are done. The system gets notified by the \textit{SessionSubsystem} based on the session, from which it received the notification, it will create and send a summary to the users within that session.

PlanningPokerAPI subsystem:
This subsystem is responsible for the fetching and manipulation of the data stored in our database. The API communicated with the database through the use of ADO.NET, which is data access technology from Microsoft .NET Framework. 

Storage subsystem:
This subsystem is responsible for managing the data from our application. It is used by several other subsystems, and can be accessed trough our \textit{PlanningPokerAPI}.
