### ISSUE TITLE
3.4  Persistent Data Management

### ISSUE THREAD

**Issue by VilfredSikker** [NoticeMeDan/planning-poker#41]
Oose s.255
Data Management.

**Comment by EliasJorgensen** [comment]
Det ville være lækkert, hvis det blev delt op i Client/Server data management, da det pt. er lidt rodet sammen. Derudover bør afsnittet ikke tage teknologi beslutninger (der bliver nævnt at Azure SQL er et oplagt valg - det var noget med deployment at gøre, det har intet med systemet at gøre).
Det er ret rodet skrevet, med meget lange sætninger. Det kunne være lækkert at få dem kortet lidt ned, så man ikke mentalt mister pusten inden man når til næste punktom.
Men det er et godt sted at starte 👌 😄
