### ISSUE TITLE
3.5  Access Control and Security

### ISSUE THREAD

**Issue by VilfredSikker** [NoticeMeDan/planning-poker#42]

**Comment by oliverjuhl** [comment]
OOSE --> Chapter: 7.4.3

**Comment by Jaqy** [comment]
![access controle](https://user-images.githubusercontent.com/17323770/48935902-7d41ab80-ef09-11e8-8a43-8558f1e9ed7a.PNG)

Jeg har lavet nogle ændring. Tilføjet flyknepper, kickuser fra session nogle getInfo til forskellige objecter. og ændret lidt navner fra startSession til bare start, da method er allerede i Session mener jeg at det er lidt overflødig.

**Comment by EliasJorgensen** [comment]
@Jaqy Fyha med det flyknepper.

**Comment by EliasJorgensen** [comment]
Synes overall at det er fint. Vi kommer ind på vores authentication, og hvordan vi håndterer vores tokens, hvilket er super. Det eneste jeg kan komme på af ændringer, er at nævne det vi snakkede om tidligere, med at der er nogle ting der er "public" (feks join session).
