### ISSUE TITLE
3.6  Global Software Control

### ISSUE THREAD

**Issue by VilfredSikker** [NoticeMeDan/planning-poker#43]
Fra Oose s. 279
Global software control describes how the global software control is implemented. In particular, this section should describe how requests are initiated and how subsystems synchronize. This section should list and address synchronization and concurrency issues.

**Comment by oliverjuhl** [comment]
OOSE --> Potentially chapter: 7.4.4

**Comment by EliasJorgensen** [comment]
All in all synes jeg at det er udemærket.
Jeg er ikke helt sikker på om man både kan have et event-based og et thread-based controlflow i samme subsystem, så der skal jeg lige have checket i bogen.
