### ISSUE TITLE
3.7  Boundary Conditions

### ISSUE THREAD

**Issue by VilfredSikker** [NoticeMeDan/planning-poker#44]

**Comment by oliverjuhl** [comment]
Reference: 7.4.6

**Comment by EliasJorgensen** [comment]
Jeg forstår ikke følgende:
`\item \textbf{The Database:} start-up is triggered through the Azure Active Directory and runs in the cloud and should be available at all time.`
Hvordan er databasen startet af Azure AD? Det samme med shut-down af databasen. Hvordan har AD indflydelse på det?

`\item \textbf{The Application:} start-up is triggered by the user upon opening the App. Upon start-up, a connection to the database is build. We retrieve data from the database through API-requests.`
Applikationen har ingen forbindelse til databasen. Det er kun API'et der kan kommunikere med databasen. Det samme med shutdown - hvorfor er databasen indeblandet i det?

Under error handling:
` we expect the users to communicate their state trough the third party program in use.`
Dette kunne godt skrives lidt mere klart, da "state" meget nemt kan forveksles med application state. "Third party program" kan også være alt mellem himmel og jord, så måske specifer at vi her mener kommunikations programmer.

Derudover ser det ganske fint ud 😄

**Comment by VilfredSikker** [comment]
Update: 
1. The Database:runs independently on its own, which means that start-up is triggered individually.

2. The Database:shut-down is triggered independently.

3. We don’t handlecommunication, so in case of a failure, we expect the users to communicate their current condition through theircommunication tool of choice.
